// The blog home (/blog/) as a hub: every page we have, grouped, findable on a
// phone. Written into theme/pchq/partials/pchq-home.hbs by ops/build-theme.mjs;
// index.hbs shows it on page 1 and keeps Ghost's card feed for /page/2+.
//
// Owner, 7 Oct 2026: "in the front page, no one is trying to read the
// articles. They're just trying to find and navigate" - and the 35 player
// pages were linked from nowhere (24 of them were not indexed). So:
//   - the sections are gen/site-nav.mjs (the dock's menus, the ONE list) plus
//     the pages no menu carries: player builds, skill-move guides, and an
//     A-Z of every post from the live sitemap, so nothing can be lost;
//   - "New" is Ghost's own list ({{#get}}), so a post published after the
//     last theme build still shows up;
//   - a filter box searches every link on the page, no request;
//   - the looks are the menus' (.pq-mg), not a new design.
import { esc } from '../gen/common.mjs';
import { NAV, hrefOf } from '../gen/site-nav.mjs';
import { PLAYERS } from '../gen/players.mjs';
import { ALL as HOWTOS } from '../gen/howto-index.mjs';

const SITE = 'https://proclubshq.com';
const UA = { headers: { Cookie: 'pchq_int=1', 'User-Agent': 'proclubshq-blog build-theme home' } };

// Every live post, with the H1 it shows (the A-Z list).
async function livePosts() {
  const xml = await (await fetch(`${SITE}/blog/sitemap-posts.xml`, UA)).text();
  const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]).filter((u) => !/\.(png|jpe?g|webp)$/.test(u));
  const out = [];
  for (let i = 0; i < urls.length; i += 8) {
    out.push(...await Promise.all(urls.slice(i, i + 8).map(async (u) => {
      const h = await (await fetch(u, UA)).text();
      const t = (h.match(/<h1[^>]*class="article-title"[^>]*>([\s\S]*?)<\/h1>/) ?? h.match(/<title>([^<]*)/))[1];
      return { href: new URL(u).pathname, title: t.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&#x27;/g, "'").replace(/&quot;/g, '"').trim() };
    })));
  }
  return out.sort((a, b) => a.title.localeCompare(b.title));
}

const link = (label, href) => `<a href="${esc(hrefOf(href))}">${esc(label)}</a>`;
const group = (title, items) => `<div class="pq-mg"><h5>${esc(title)}</h5>${items.map(([l, h]) => link(l, h)).join('')}</div>`;
const section = (id, title, blurb, body, cls = '') => `<section class="ph-sec${cls}" id="${id}">
<h2>${esc(title)}</h2><p class="ph-blurb">${esc(blurb)}</p>
${body}
</section>`;

export async function blogHome() {
  const posts = await livePosts();
  const live = new Set(posts.map((p) => p.href));
  const players = PLAYERS.map((p) => [p.name, `/blog/${p.slug}-pro-clubs-build/`]).filter(([, h]) => live.has(h))
    .sort((a, b) => a[0].localeCompare(b[0]));
  const skills = HOWTOS.filter((h) => h.published && live.has(h.href)).map((h) => [h.name, h.href]).sort((a, b) => a[0].localeCompare(b[0]));
  const navSections = NAV.map((s) => section(`h-${s.key}`, s.label, s.blurb,
    `<div class="pq-mgs">${s.groups.map(([g, items]) => group(g, items)).join('')}</div>`));
  // The skill-move guides sit beside the dock's Guides section.
  const gi = NAV.findIndex((s) => s.key === 'guides');
  navSections.splice(gi + 1, 0, section('h-skills', 'Skill move guides', 'Every new FC 27 skill move: the PS5 and Xbox input, animated.',
    `<div class="pq-mgs ph-cols">${group('How to do', skills)}</div>`));
  const bi = NAV.findIndex((s) => s.key === 'builds');
  navSections.splice(bi + 1, 0, section('h-players', 'Player builds', 'Real footballers as FC 27 Pro Clubs builds, free to copy.',
    `<div class="pq-mgs ph-cols">${group(`${players.length} players`, players)}</div>`));

  const az = posts.map((p) => `<a href="${esc(p.href)}">${esc(p.title)}</a>`).join('');
  const html = `{{!-- GENERATED by ops/build-theme.mjs (ops/blog-home.mjs). Do not edit. --}}
<div class="ph" id="ph">
<header class="ph-top">
<h1>FC 27 Pro Clubs guides, builds and tools</h1>
<p>Every page on the Pro Clubs HQ blog, grouped: archetype cheat sheets, builds by position, real-player builds, calculators, the meta and the controls.</p>
<input class="ph-find" id="ph-find" type="search" placeholder="Find a page: Magician, CDM, Haaland, roulette…" aria-label="Find a page on this blog" autocomplete="off">
<p class="ph-none" id="ph-none" hidden>Nothing on this page matches. Try the search in the header.</p>
<nav class="ph-jump" aria-label="Sections">${[...NAV.map((s) => [s.label, `h-${s.key}`]), ['Players', 'h-players'], ['Skill moves', 'h-skills'], ['A–Z', 'h-az']]
    .map(([l, id]) => `<a href="#${id}">${esc(l)}</a>`).join('')}</nav>
</header>
<section class="ph-sec" id="h-new">
<h2>New on the blog</h2>
<div class="ph-new">{{#get "posts" limit="6" order="published_at desc"}}{{#foreach posts}}<a href="{{url}}"><b>{{title}}</b><span>{{date published_at format="D MMM"}}</span></a>{{/foreach}}{{/get}}</div>
</section>
${navSections.join('\n')}
<section class="ph-sec" id="h-az">
<h2>Every article, A to Z</h2><p class="ph-blurb">${posts.length} articles.</p>
<details class="ph-az"><summary>Show all ${posts.length}</summary><div class="ph-azl">${az}</div></details>
</section>
</div>
<script>(function(){var f=document.getElementById('ph-find'),r=document.getElementById('ph'),n=document.getElementById('ph-none');if(!f)return;
f.addEventListener('input',function(){var q=f.value.trim().toLowerCase(),any=false,d=r.querySelector('.ph-az');if(d&&q)d.open=true;
r.querySelectorAll('.ph-sec').forEach(function(s){var hit=0;s.querySelectorAll('a').forEach(function(a){var ok=!q||a.textContent.toLowerCase().indexOf(q)>-1;a.hidden=!ok;if(ok)hit++;});
s.querySelectorAll('.pq-mg').forEach(function(g){g.hidden=q&&!g.querySelector('a:not([hidden])');});s.hidden=q&&!hit;if(hit)any=true;});n.hidden=!q||any;});})();</script>
`;
  const links = [...new Set([...html.matchAll(/href="(\/blog\/[^"#]*)"/g)].map((m) => m[1]))];
  return { html, posts: posts.length, players: players.length, skills: skills.length, links };
}
