// Builds the blog's Ghost theme, `pchq` (theme/pchq): Casper 5.12.1 with our
// header, the icon dock and its menus.
//
//   1. partials/pchq-nav.hbs   written from gen/site-nav.mjs (the ONE list of
//                              menu pages); every blog link is fetched from the
//                              live site and must answer 200, every app link is
//                              written to out/_nav.html for ops/link-sweep.mjs
//   2. assets/built/pchq.css   assets/css/pchq.css, comments stripped
//   3. assets/built/pchq.js    photoswipe + Casper's infinite scroll and
//                              lightbox + assets/js/pchq-nav.js, concatenated
//   4. theme/pchq.zip          what ops/theme-deploy.mjs uploads (zips are
//                              git-ignored; the folder is the source)
//   5. gscan, Ghost's own theme validator, when GSCAN points at its binary
//
//     ~/.local/node22/bin/node ops/build-theme.mjs
//     GSCAN=/path/to/node_modules/.bin/gscan ~/.local/node22/bin/node ops/build-theme.mjs
//
// Deploy and roll back: DEPLOYMENT.md "The blog theme".
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import { NAV, hrefOf, navLinks } from '../gen/site-nav.mjs';

const ROOT = path.join(import.meta.dirname, '..');
const T = path.join(ROOT, 'theme', 'pchq');
const SITE = 'https://proclubshq.com';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
for (const { label, href } of navLinks()) if (/\{\{|grounds/i.test(label + href.replace(/fc27-the-grounds-pro-clubs-explained/, ''))) throw new Error(`nav: "${label}" has a handlebars brace or names The Grounds`);

// ── 1. the nav partial ──────────────────────────────────────────────────────
const svg = (d) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const partial = `{{!-- GENERATED by ops/build-theme.mjs from gen/site-nav.mjs. Do not edit. --}}
<header class="pq-head" id="pq-head">
    <div class="pq-head-in">
        <a class="pq-logo" href="{{@site.url}}" aria-label="{{@site.title}} blog">{{#if @site.logo}}<img src="{{@site.logo}}" alt="" width="34" height="34">{{/if}}<span>PRO CLUBS <i>HQ</i></span></a>
        <nav class="pq-dock" aria-label="Sections">
${NAV.map((s) => `            <button class="pq-di" type="button" data-m="${s.key}" aria-controls="pq-m-${s.key}" aria-expanded="false">${svg(s.icon)}<span>${esc(s.label)}</span></button>`).join('\n')}
        </nav>
        <span class="pq-sp"></span>
        <button class="pq-search" type="button" aria-label="Search this site" data-ghost-search>{{> "icons/search"}}</button>
        <a class="pq-cta" href="${hrefOf('app:/')}">Open the app</a>
    </div>
</header>
<div class="pq-scrim" id="pq-scrim"></div>
<div class="pq-menu" id="pq-menu">
${NAV.map((s) => `    <div class="pq-mp" id="pq-m-${s.key}">
        <div class="pq-mh"><b>${esc(s.label)}</b><span>${esc(s.blurb)}</span></div>
        <div class="pq-mgs">
${s.groups.map(([g, items]) => `            <div class="pq-mg"><h5>${esc(g)}</h5>${items.map(([l, h]) => `<a href="${esc(hrefOf(h))}">${esc(l)}</a>`).join('')}</div>`).join('\n')}
        </div>
    </div>`).join('\n')}
</div>
<noscript><style>.pq-dock{display:none}.pq-menu{display:block;position:static;max-height:none}.pq-mp{display:block}</style></noscript>
`;
writeFileSync(path.join(T, 'partials', 'pchq-nav.hbs'), partial);

// Every menu link answers. A Ghost page that does not exist is a real 404
// (unlike the app, whose shell answers 200 for anything - those go through
// the link sweep's router list instead).
const links = navLinks();
let bad = 0;
for (const { label, href } of links.filter((l) => !l.href.startsWith('app:'))) {
  const r = await fetch(SITE + href, { redirect: 'manual', headers: { Cookie: 'pchq_int=1', 'User-Agent': 'proclubshq-blog build-theme linksweep' } });
  if (r.status !== 200) { bad++; console.error(`  !! ${label}: ${href} -> ${r.status}`); }
}
if (bad) throw new Error(`${bad} menu links do not answer 200`);
mkdirSync(path.join(ROOT, 'out'), { recursive: true });
writeFileSync(path.join(ROOT, 'out', '_nav.html'), links.filter((l) => l.href.startsWith('app:')).map((l) => `<a href="${esc(hrefOf(l.href))}">${esc(l.label)}</a>`).join('\n') + `\n<a href="${hrefOf('app:/')}">Open the app</a>\n`);
console.log(`nav: ${NAV.length} sections, ${links.length} links (${links.filter((l) => !l.href.startsWith('app:')).length} blog pages answered 200; app links -> out/_nav.html for the link sweep)`);

// ── 2 + 3. built assets ─────────────────────────────────────────────────────
mkdirSync(path.join(T, 'assets', 'built'), { recursive: true });
const css = readFileSync(path.join(T, 'assets', 'css', 'pchq.css'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s*\n\s*/g, '').replace(/\s*([{};,])\s*/g, '$1').replace(/;}/g, '}');
writeFileSync(path.join(T, 'assets', 'built', 'pchq.css'), css);
const js = ['lib/photoswipe.min.js', 'lib/photoswipe-ui-default.min.js', 'infinite-scroll.js', 'lightbox.js', 'pchq-nav.js']
  .map((f) => `/* ${f} */\n${readFileSync(path.join(T, 'assets', 'js', f), 'utf8')}`).join('\n;\n');
writeFileSync(path.join(T, 'assets', 'built', 'pchq.js'), js);
console.log(`built: pchq.css ${css.length} bytes, pchq.js ${js.length} bytes`);

// ── 4. the zip ──────────────────────────────────────────────────────────────
const zip = path.join(ROOT, 'theme', 'pchq.zip');
if (existsSync(zip)) rmSync(zip);
execFileSync('zip', ['-q', '-r', zip, '.', '-x', '.*', '-x', 'assets/css/*', '-x', 'assets/js/*'], { cwd: T });
console.log(`-> theme/pchq.zip (${Math.round(readFileSync(zip).length / 1024)} KB)`);

// ── 5. gscan ────────────────────────────────────────────────────────────────
if (process.env.GSCAN) {
  try { console.log(execFileSync(process.env.GSCAN, [T], { encoding: 'utf8' })); }
  catch (e) { console.log(e.stdout ?? ''); throw new Error('gscan reported errors'); }
} else console.log('gscan skipped (set GSCAN to its binary); Ghost runs it again on upload and refuses a theme with errors');
