// Builds the blog's Ghost theme, `pchq` (theme/pchq): Casper 5.12.1 with our
// header, the icon dock and its menus.
//
//   1. partials/pchq-nav.hbs   written from gen/site-nav.mjs (the ONE list of
//                              menu pages); every blog link is fetched from the
//                              live site and must answer 200, every app link is
//                              written to out/_nav.html for ops/link-sweep.mjs
//   2. assets/built/pchq.css   assets/css/pchq.css, comments stripped
//   3. assets/built/pchq.js    photoswipe + Casper's infinite scroll and
//                              lightbox + assets/js/pchq-nav.js, concatenated
//   4. theme/pchq.zip          what ops/theme-deploy.mjs uploads (zips are
//                              git-ignored; the folder is the source)
//   5. gscan, Ghost's own theme validator, when GSCAN points at its binary
//
//     ~/.local/node22/bin/node ops/build-theme.mjs
//     GSCAN=/path/to/node_modules/.bin/gscan ~/.local/node22/bin/node ops/build-theme.mjs
//
// Deploy and roll back: DEPLOYMENT.md "The blog theme".
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { blogHome } from './blog-home.mjs';
import path from 'node:path';
import { NAV, hrefOf, navLinks } from '../gen/site-nav.mjs';
import { guidesIndex } from './guides-index.mjs';
import { header as chromeHeader, sheet as chromeSheet, dock as chromeDock } from './app-chrome.mjs';

const ROOT = path.join(import.meta.dirname, '..');
const T = path.join(ROOT, 'theme', 'pchq');
const SITE = 'https://proclubshq.com';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
for (const { label, href } of navLinks()) if (/\{\{|grounds/i.test(label + href.replace(/fc27-the-grounds-pro-clubs-explained/, ''))) throw new Error(`nav: "${label}" has a handlebars brace or names The Grounds`);

// ── 1. the nav partial ──────────────────────────────────────────────────────
// Since #485 (10 Oct 2026) the APP's header, Guides sheet and dock
// (ops/app-chrome.mjs): one suite. The six sections' pages are the sheet's
// links, still in every page's HTML.
const partial = `{{!-- GENERATED by ops/build-theme.mjs (ops/app-chrome.mjs, gen/site-nav.mjs). Do not edit. --}}
${chromeHeader()}
${chromeSheet()}
${chromeDock()}
<noscript><style>.pq-gs{display:block!important;position:static;max-height:none;transform:none}.pq-gs-p{display:block!important}.pq-gs-scrim{display:none}</style></noscript>
`;
writeFileSync(path.join(T, 'partials', 'pchq-nav.hbs'), partial);

// The blog home hub (ops/blog-home.mjs): every page, grouped, on /blog/ page 1.
const home = await blogHome();
writeFileSync(path.join(T, 'partials', 'pchq-home.hbs'), home.html);
console.log(`home: ${home.posts} posts A-Z, ${home.players} players, ${home.skills} skill guides, ${home.links.length} blog links`);

// The app's index of the blog (#485, ops/guides-index.mjs): published to
// Ghost's files by ops/theme-deploy.mjs; `--app` also copies it into the app.
const gi = guidesIndex(home);
mkdirSync(path.join(ROOT, 'out'), { recursive: true });
writeFileSync(path.join(ROOT, 'out', 'guides-index.json'), JSON.stringify(gi));
console.log(`guides-index: ${gi.nav.length} sections, ${gi.articles.length} articles -> out/guides-index.json`);
if (process.argv.includes('--app')) {
  const APP = process.env.APP_REPO ?? path.join(process.env.HOME, 'Desktop', 'Claude', 'ClubsUI-main');
  writeFileSync(path.join(APP, 'frontend', 'src', 'data', 'guidesIndex.json'), JSON.stringify(gi, null, 1) + '\n');
  console.log(`  copied to ${APP}/frontend/src/data/guidesIndex.json`);
}

// Every menu link answers. A Ghost page that does not exist is a real 404
// (unlike the app, whose shell answers 200 for anything - those go through
// the link sweep's router list instead).
const links = navLinks();
let bad = 0;
for (const { label, href } of links.filter((l) => !l.href.startsWith('app:'))) {
  const r = await fetch(SITE + href, { redirect: 'manual', headers: { Cookie: 'pchq_int=1', 'User-Agent': 'proclubshq-blog build-theme linksweep' } });
  if (r.status !== 200) { bad++; console.error(`  !! ${label}: ${href} -> ${r.status}`); }
}
if (bad) throw new Error(`${bad} menu links do not answer 200`);
mkdirSync(path.join(ROOT, 'out'), { recursive: true });
writeFileSync(path.join(ROOT, 'out', '_nav.html'), links.filter((l) => l.href.startsWith('app:')).map((l) => `<a href="${esc(hrefOf(l.href))}">${esc(l.label)}</a>`).join('\n') + '\n' + ['/?dock=home', '/lobby', '/companion', '/controls', '/inbox', '/my-builds', '/explore', '/create', '/meta']
  .map((p) => `<a href="${hrefOf(`app:${p}`)}">header/dock ${p}</a>`).join('\n') + '\n');
console.log(`nav: ${NAV.length} sections, ${links.length} links (${links.filter((l) => !l.href.startsWith('app:')).length} blog pages answered 200; app links -> out/_nav.html for the link sweep)`);

// ── 2 + 3. built assets ─────────────────────────────────────────────────────
mkdirSync(path.join(T, 'assets', 'built'), { recursive: true });
const css = readFileSync(path.join(T, 'assets', 'css', 'pchq.css'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s*\n\s*/g, '').replace(/\s*([{};,])\s*/g, '$1').replace(/;}/g, '}');
writeFileSync(path.join(T, 'assets', 'built', 'pchq.css'), css);
const js = ['lib/photoswipe.min.js', 'lib/photoswipe-ui-default.min.js', 'infinite-scroll.js', 'lightbox.js', 'pchq-nav.js']
  .map((f) => `/* ${f} */\n${readFileSync(path.join(T, 'assets', 'js', f), 'utf8')}`).join('\n;\n');
writeFileSync(path.join(T, 'assets', 'built', 'pchq.js'), js);
console.log(`built: pchq.css ${css.length} bytes, pchq.js ${js.length} bytes`);

// ── 4. the zip ──────────────────────────────────────────────────────────────
const zip = path.join(ROOT, 'theme', 'pchq.zip');
if (existsSync(zip)) rmSync(zip);
execFileSync('zip', ['-q', '-r', zip, '.', '-x', '.*', '-x', 'assets/css/*', '-x', 'assets/js/*'], { cwd: T });
console.log(`-> theme/pchq.zip (${Math.round(readFileSync(zip).length / 1024)} KB)`);

// ── 5. gscan ────────────────────────────────────────────────────────────────
if (process.env.GSCAN) {
  try { console.log(execFileSync(process.env.GSCAN, [T], { encoding: 'utf8' })); }
  catch (e) { console.log(e.stdout ?? ''); throw new Error('gscan reported errors'); }
} else console.log('gscan skipped (set GSCAN to its binary); Ghost runs it again on upload and refuses a theme with errors');
